version: '2'

services:
  db:
    image: postgres:11.3
    ports:
      - 5432:5432
    volumes:
      - ./tools/db_init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=librarychecker
      - POSTGRES_PASSWORD=passwd
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "librarychecker", "-U", "postgres" ]
        timeout: 10s
        interval: 1s
        retries: 30

  minio:
    image: minio/minio
    command: server /data
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniopass

  api:
    build:
      dockerfile: Dockerfile.API
    command: -pghost=db -hmackey=dummy_secret
    ports:
      - 50051:50051
    depends_on:
      db:
        condition: service_healthy
    environment:
      - API_DB_LOG=true
    healthcheck:
        test: grpc_health_probe -addr localhost:50051
        timeout: 10s
        interval: 1s
        retries: 30

  api-grpcweb:
    build:
      dockerfile: Dockerfile.API
    command: -grpcweb -pghost=db -hmackey=dummy_secret
    ports:
      - 58080:50051
    depends_on:
      db:
        condition: service_healthy
    environment:
      - API_DB_LOG=true
    healthcheck:
        test: wget -q -O - localhost:50051/health || exit 1
        timeout: 10s
        interval: 1s
        retries: 30
