name: API-Deploy

on:
  push:
    branches: 
      - patch/actions

jobs:
  api-deploy:
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: projects/190778459730/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
        service_account: cloud-run-deployer@library-checker-project.iam.gserviceaccount.com

    - id: gen-protoc
      name: gen protoc
      run: ./api/gen_protoc.sh
