name: API-Deploy

on:
  push:
    branches: 
      - master
      - test/secret

jobs:
  api-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        workload_identity_provider: projects/190778459730/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider
        service_account: cloud-run-deployer@library-checker-project.iam.gserviceaccount.com
        token_format: access_token
    
    - uses: docker/login-action@v1
      with:
        registry: asia.gcr.io
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - id: gen-protoc
      name: Generate protoc
      run: ./api/gen_protoc.sh

    - id: build-docker
      name: Build docker image
      run: docker build -t asia.gcr.io/library-checker-project/judge-api-test -f Dockerfile.API .

    - id: push-docker
      name: Push docker image
      run: docker push asia.gcr.io/library-checker-project/judge-api-test

    # TODO: migrate to google-github-actions/deploy-cloudrun@v0
    - id: setup-cloud-sdk
      name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - id: deploy-api
      name: Deploy API to Cloud Run
      run: >
        gcloud run deploy
        judge-api-test
        --image=asia.gcr.io/library-checker-project/judge-api-test
        --platform=managed
        --region=asia-northeast1
        --add-cloudsql-instances=library-checker-sql
        --set-env-vars=HMAC_SECRET="$HMAC_SECRET"
        --args=-pghost=/cloudsql/library-checker-project:asia-northeast1:library-checker-sql,-pgpass-secret=projects/190778459730/secrets/postgre-pass/versions/latest
        --service-account=cloud-run-api@library-checker-project.iam.gserviceaccount.com
        --max-instances=10
      env:
        HMAC_SECRET: ${{ secrets.HMAC_SECRET }}

    - id: deploy-grpcweb-api
      name: Deploy API(gRPC) to Cloud Run
      run: >
        gcloud run deploy
        judge-grpcweb-api-test
        --image=asia.gcr.io/library-checker-project/judge-api-test
        --platform=managed
        --region=asia-northeast1
        --args=-grpcweb,-pghost=/cloudsql/library-checker-project:asia-northeast1:library-checker-sql,-pgpass-secret=projects/190778459730/secrets/postgre-pass/versions/latest
        --add-cloudsql-instances=library-checker-sql
        --set-env-vars=HMAC_SECRET="$HMAC_SECRET",MODE=gRPCWeb
        --service-account=cloud-run-api@library-checker-project.iam.gserviceaccount.com
        --max-instances=10
      env:
        HMAC_SECRET: ${{ secrets.HMAC_SECRET }}
